services:
  portainer:
    image: portainer/portainer-ce:2.22.0
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/letsencrypt/live/portainer.homelab.local:/certs/live/portainer.homelab.local:ro
      - /etc/letsencrypt/archive/portainer.homelab.local:/certs/archive/portainer.homelab.local:ro

    command:
      - "--sslcert"
      - "/certs/live/portainer.homelab.local/fullchain.pem"
      - "--sslkey"
      - "/certs/live/portainer.homelab.local/privkey.pem"

volumes:
  portainer_data:
   name: portainer_data
